export const COLABORADOR_REGISTRADO_EXITOSO_CREADO  = 'COLABORADOR_REGISTRADO_EXITOSO_CREADO ';
export const COLABORADOR_REGISTRADO_EXITOSO_MENSAJE = 'COLABORADOR_REGISTRADO_EXITOSO_MENSAJE'
export const COLABORADOR_REGISTRADO_ERROR = 'COLABORADOR_ERROR';

export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const USUARIO_AUTENTICADO = 'USUARIO_AUTENTICADO';
export const CERRAR_SESION = 'CERRAR_SESION'

export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';


export const LIMPIAR_STATE = 'LIMPIAR_STATE';

export const AGREGAR_PASSWORD = 'AGREGAR_PASSWORD';
